# Site
name: "MLAI Blog"
title: "MLAI Blog"
description: "Yet Another Machine Learning and Data Science Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /mlai-blog
google_analytics: 'UA-169172566-1'
disqus: ''
mailchimp-list: false
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  pawan:
    name: Pawan Lamba
    display_name: Pawan
    avatar: assets/images/gravatar.jpeg
    email: pawanlamba17@gmail.com
    web: https://www.pawanlamba.com
    twitter: https://twitter.com/PawanLamba
    linkedin: https://www.linkedin.com/in/pawanlamba/
    description: "Just another ML and AI guy"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 3
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, about.md]
